"""Artifact-only rendering. Used when the Reporter's model call fails, so the PR
is never blocked on prose it could not get."""

from __future__ import annotations

from principal.db.store import Task


def render_fallback_body(goal: str, verified: list[Task], discarded: list[Task], uncovered: list[str]) -> str:
    lines = [f"Automated migration: {goal}", "", "## Verified changes"]
    for t in verified:
        lines.append(f"- `{t.target_file}`: {t.instruction}")
    if discarded:
        lines += ["", "## Not migrated"]
        for t in discarded:
            lines.append(f"- `{t.target_file}`: {t.discard_reason or 'unknown reason'}")
    if uncovered:
        lines += ["", "## Risk: modified with no test coverage"]
        for f in uncovered:
            lines.append(f"- `{f}`")
    lines += ["", "---", "_Generated by Principal. Every claim above is backed by a sandbox operation id",
              "and a test log in the job's published trace._"]
    return "\n".join(lines)
