"""Artifact-only rendering. Used when the Reporter's model call fails, so the PR
is never blocked on prose it could not get."""

from __future__ import annotations

from principal.db.store import Task


def render_fallback_body(
    goal: str, verified: list[Task], discarded: list[Task], uncovered: list[str], *,
    characterisation_only: list[str] | None = None, characterisation_result: dict | None = None,
    relocated_symbols: list[str] | None = None, unresolved_call_sites: list[dict] | None = None,
) -> str:
    asked = [t for t in verified if t.kind != "cleanup"]
    cleanup = [t for t in verified if t.kind == "cleanup"]

    lines = [f"Automated migration: {goal}", "", "## Verified changes"]
    for t in asked:
        lines.append(f"- `{t.target_file}`: {t.instruction}")
    if cleanup:
        lines += ["", "## Cleanup (dead code this refactor orphaned, not part of the requested change)"]
        for t in cleanup:
            lines.append(f"- `{t.target_file}`: {t.instruction}")
    if discarded:
        lines += ["", "## Not migrated"]
        for t in discarded:
            lines.append(f"- `{t.target_file}`: {t.discard_reason or 'unknown reason'}")
    if uncovered:
        lines += ["", "## Risk: modified with no test coverage"]
        for f in uncovered:
            lines.append(f"- `{f}`")
    if characterisation_only:
        lines += ["", "## Risk: verified only by a generated test, not a pre-existing one"]
        mutation = (characterisation_result or {}).get("mutation") or {}
        score = mutation.get("score")
        note = f" (mutation score {score:.2f})" if isinstance(score, (int, float)) else ""
        for f in characterisation_only:
            lines.append(f"- `{f}`{note}")
    if relocated_symbols:
        lines += ["", "## Relocated symbols (moved, not removed — check the new import path)"]
        for s in relocated_symbols:
            lines.append(f"- `{s}`")
    if unresolved_call_sites:
        lines += ["", "## Call sites the graph could not resolve statically"]
        for s in unresolved_call_sites:
            lines.append(f"- `{s['file']}:{s['line']}` — {s['name']} ({s['reason']})")
    lines += ["", "---", "_Generated by Principal. Every claim above is backed by a sandbox operation id",
              "and a test log in the job's published trace._"]
    return "\n".join(lines)
